export const dummyRally = {
  id: 'clw6oduid006ixxooqm6wfrf8',
  title: '랠리 2',
  description: '2번 랠리에 대한 설명입니다.',
  status: 'active',
  kit: {
    id: 147,
    title: '키트 15',
    description: '15번 키트의 설명입니다.',
    tags: '6일_챌린지',
    thumbnailImage: 'https://picsum.photos/360',
    rewardImage: 'https://picsum.photos/360',
    uploaderId: 'clw6oducw000mxxooub0g7cux',
    createdAt: '2024-05-14T17:37:14.517Z',
    updatedAt: null,
    deletedAt: null,
  },
  starter: {
    id: 'clw6oducf000bxxooiphc41al',
    email: 'user22@example.com',
    profileImage: 'https://picsum.photos/360',
    nickname: 'User22',
    twitterId: null,
    authToken: null,
    authProvider: 'twitter',
    createdAt: '2024-05-14T17:37:14.346Z',
    updatedAt: null,
    deletedAt: null,
  },
  stampCount: 1,
};

export const dummyRallies = [
  {
    id: 'clw6oduid006ixxooqm6wfrf8',
    title: '랠리 2',
    description: '2번 랠리에 대한 설명입니다.',
    status: 'active',
    kit: {
      id: 147,
      title: '키트 15',
      description: '15번 키트의 설명입니다.',
      tags: '6일_챌린지',
      thumbnailImage: 'https://picsum.photos/360',
      rewardImage: 'https://picsum.photos/360',
      uploaderId: 'clw6oducw000mxxooub0g7cux',
      createdAt: '2024-05-14T17:37:14.517Z',
      updatedAt: null,
      deletedAt: null,
    },
    starter: {
      id: 'clw6oducf000bxxooiphc41al',
      email: 'user22@example.com',
      profileImage: 'https://picsum.photos/360',
      nickname: 'User22',
      twitterId: null,
      authToken: null,
      authProvider: 'twitter',
      createdAt: '2024-05-14T17:37:14.346Z',
      updatedAt: null,
      deletedAt: null,
    },
    stampCount: 1,
  },
  {
    id: 'clw6oduid006ixxooqm6wfrf8',
    title: '랠리 2',
    description: '2번 랠리에 대한 설명입니다.',
    status: 'active',
    kit: {
      id: 147,
      title: '키트 15',
      description: '15번 키트의 설명입니다.',
      tags: '6일_챌린지',
      thumbnailImage: 'https://picsum.photos/360',
      rewardImage: 'https://picsum.photos/360',
      uploaderId: 'clw6oducw000mxxooub0g7cux',
      createdAt: '2024-05-14T17:37:14.517Z',
      updatedAt: null,
      deletedAt: null,
    },
    starter: {
      id: 'clw6oducf000bxxooiphc41al',
      email: 'user22@example.com',
      profileImage: 'https://picsum.photos/360',
      nickname: 'User22',
      twitterId: null,
      authToken: null,
      authProvider: 'twitter',
      createdAt: '2024-05-14T17:37:14.346Z',
      updatedAt: null,
      deletedAt: null,
    },
    stampCount: 1,
  },
  {
    id: 'clw6oduid006ixxooqm6wfrf8',
    title: '랠리 2',
    description: '2번 랠리에 대한 설명입니다.',
    status: 'active',
    kit: {
      id: 147,
      title: '키트 15',
      description: '15번 키트의 설명입니다.',
      tags: '6일_챌린지',
      thumbnailImage: 'https://picsum.photos/360',
      rewardImage: 'https://picsum.photos/360',
      uploaderId: 'clw6oducw000mxxooub0g7cux',
      createdAt: '2024-05-14T17:37:14.517Z',
      updatedAt: null,
      deletedAt: null,
    },
    starter: {
      id: 'clw6oducf000bxxooiphc41al',
      email: 'user22@example.com',
      profileImage: 'https://picsum.photos/360',
      nickname: 'User22',
      twitterId: null,
      authToken: null,
      authProvider: 'twitter',
      createdAt: '2024-05-14T17:37:14.346Z',
      updatedAt: null,
      deletedAt: null,
    },
    stampCount: 1,
  },
  {
    id: 'clw6oduid006ixxooqm6wfrf8',
    title: '랠리 2',
    description: '2번 랠리에 대한 설명입니다.',
    status: 'active',
    kit: {
      id: 147,
      title: '키트 15',
      description: '15번 키트의 설명입니다.',
      tags: '6일_챌린지',
      thumbnailImage: 'https://picsum.photos/360',
      rewardImage: 'https://picsum.photos/360',
      uploaderId: 'clw6oducw000mxxooub0g7cux',
      createdAt: '2024-05-14T17:37:14.517Z',
      updatedAt: null,
      deletedAt: null,
    },
    starter: {
      id: 'clw6oducf000bxxooiphc41al',
      email: 'user22@example.com',
      profileImage: 'https://picsum.photos/360',
      nickname: 'User22',
      twitterId: null,
      authToken: null,
      authProvider: 'twitter',
      createdAt: '2024-05-14T17:37:14.346Z',
      updatedAt: null,
      deletedAt: null,
    },
    stampCount: 1,
  },
];
