export const DEFAULT_PROFILE = '/default-profile.svg';
export const DEFAULT_KIT_THUMBNAIL = '/kkuk-kkuk.svg';
export const MY_PAGE_PATH = '/my';
export const TWITTER_ACCOUNT_ID = '';
export const DATE_TO_MS = 1000 * 60 * 60 * 24;
export const MAKING_MESSAGE = '준비 중인 기능입니다';
export const DOMAIN = process.env.DOMAIN!;
export const AUTO_TWEET = encodeURI('제가 만든 키트로 릴레이를 시작해보세요!');
export const AUTO_TWEET_HASHTAGS = '꾹꾹,kookkook';
export const MAXIMUM_TAGS = 6;
export const API_URL = process.env.API_URL!;
export const MIN_RALLY_DEADLINE_DAYS = 7;
export const MAX_RALLY_DEADLINE_DAYS = 100;

export const REGION = process.env.AWS_REGION!;
export const ACCESS_KEY_ID = process.env.AWS_ACCESS_KEY_ID!;
export const SECRET_ACCESS_KEY = process.env.AWS_SECRET_ACCESS_KEY!;
export const BUCKET_NAME = process.env.AWS_S3_BUCKET_NAME!;
export const BASE_KEY = process.env.AWS_S3_BASE_KEY!;
